version: '3.8'

services:
  ansible-controller:
    image: ubuntu:20.04
    container_name: ansible-controller
    command: /bin/bash -c "apt-get update && apt-get install -y ansible sshpass && /bin/bash"
    networks:
      - ansible-network
    volumes:
      - ./ansible:/workspace

  ansible-node:
    image: ubuntu:20.04
    container_name: ansible-node
    command: /bin/bash -c "apt-get update && apt-get install -y openssh-server && service ssh start && /bin/bash"
    networks:
      - ansible-network
    deploy:
      replicas: 5

networks:
  ansible-network:
    driver: bridge